apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dotnet-api
  template:
    metadata:
      labels:
        app: dotnet-api
    spec:
      containers:
        - name: dotnet-api-container
          image: cloudnxt/dotnetapi:v1
          ports:
            - containerPort: 80
          securityContext:
            runAsUser: 1000 # Replace with your desired user ID
            runAsGroup: 1000 # Replace with your desired group ID
            capabilities:
              drop:
              - all
            readOnlyRootFilesystem: true