apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-api
  template:
    metadata:
      labels:
        app: node-api
    spec:
      containers:
      - name: node-api-container
        image: cloudnxt/nodeapp:v1
        ports:
        - containerPort: 3000
        
        resources:
          limits:
            cpu: 200m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 200Mi
        securityContext:
          runAsUser: 1000 # Replace with your desired user ID
          runAsGroup: 1000 # Replace with your desired group ID
          capabilities:
            drop:
            - all
          readOnlyRootFilesystem: true
