apiVersion: v1
kind: Service
metadata:
  name: ng-frontend-deployment
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 31000
  type: NodePort
  selector:
    app: ng-frontend
status:
  loadBalancer: {}